import type { Metadata } from "next";
import { Space_Grotesk, Geist_Mono } from "next/font/google";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import "./globals.css";

const spaceGrotesk = Space_Grotesk({
  variable: "--font-space-grotesk",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${spaceGrotesk.variable} ${geistMono.variable}`}
      data-bs-theme="dark"
      data-theme-shade="dark"
    >
      <head>
        <link rel="stylesheet" href="/vendor/bootstrap.min.css" />
      </head>
      <body className="app-body">
        <Header />
        {children}
        <Footer />
        <script src="/vendor/bootstrap.bundle.min.js" defer></script>
        <script src="/js/theme-toggle.js" defer></script>
        <script src="/js/ink-cursor.js" defer></script>
      </body>
    </html>
  );
}
